import "./globals.css";
import AppHeader from "@/components/layout/AppHeader";
import type { Metadata } from "next";
import ThemeProvider from "@/context/ThemeProvider";
import clsx from "clsx";
import { fontVariables } from "@/assets/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={clsx(
            fontVariables,
            "mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0 antialiased",
          )}
        >
          <AppHeader />

          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
