import "./globals.css";
import AppHeader from "@/components/Layout/AppHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "./ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dim">
      <ThemeProvider>
        <body className={inter.className}>
          <AppHeader />

          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
